name: G2B Notice Check

on:
  schedule:
      - cron: '*/30 * * * *'
        worflow_dispatch:

        permissions:
          contents: write

          concurrency:
            group: bid-check
              cancel-in-progress: false

              
